inherit_from: .rubocop_todo.yml
require: rubocop-rspec

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

RSpec/ExpectActual:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.5
