Style/MethodCallWithoutArgsParentheses:
  Exclude:
    - 'interactive_brokers_proxy/lib/interactive_brokers_proxy/app/java_ext/**/*'

Style/ClassAndModuleChildren:
  Exclude:
    - 'interactive_brokers_proxy/lib/interactive_brokers_proxy/app/java_ext/**/*'

Style/FrozenStringLiteralComment:
  Exclude:
    - 'interactive_brokers_proxy/lib/interactive_brokers_proxy/app/java_ext/**/*'

Metrics/MethodLength:
  Exclude:
    - 'interactive_brokers_common/lib/interactive_brokers_common/common/**/*'
    - 'interactive_brokers_proxy/lib/interactive_brokers_proxy/app/java_ext/**/*'

Layout/LineLength:
  Exclude:
    - 'interactive_brokers_common/lib/interactive_brokers_common/common/**/*'
    - 'interactive_brokers_proxy/lib/interactive_brokers_proxy/app/java_ext/**/*'

Metrics/ParameterLists:
  Exclude:
    - 'interactive_brokers_common/lib/interactive_brokers_common/common/**/*'
    - 'interactive_brokers_proxy/lib/interactive_brokers_proxy/app/java_ext/**/*'

Metrics/AbcSize:
  Exclude:
    - 'interactive_brokers_common/lib/interactive_brokers_common/common/**/*'
    - 'interactive_brokers_proxy/lib/interactive_brokers_proxy/app/java_ext/**/*'

Metrics/ClassLength:
  Exclude:
    - 'interactive_brokers_common/lib/interactive_brokers_common/common/**/*'
    - 'interactive_brokers_proxy/lib/interactive_brokers_proxy/app/java_ext/**/*'

Metrics/ModuleLength:
  Exclude:
    - 'interactive_brokers_common/lib/interactive_brokers_common/common/**/*'
    - 'interactive_brokers_proxy/lib/interactive_brokers_proxy/app/java_ext/**/*'

Metrics/PerceivedComplexity:
  Exclude:
    - 'interactive_brokers_common/lib/interactive_brokers_common/common/**/*'
    - 'interactive_brokers_proxy/lib/interactive_brokers_proxy/app/java_ext/**/*'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'interactive_brokers_common/lib/interactive_brokers_common/common/**/*'
    - 'interactive_brokers_proxy/lib/interactive_brokers_proxy/app/java_ext/**/*'

Style/DoubleNegation:
  Exclude:
    - 'interactive_brokers_common/lib/interactive_brokers_common/common/**/*'

Lint/StructNewOverride:
  Exclude:
    - 'interactive_brokers_common/lib/interactive_brokers_common/common/**/*'
