inherit_from:
  - .rubocop_todo.yml
  - .rubocop_excludes_for_generator.yml
require: rubocop-rspec

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

RSpec/ExpectActual:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  Exclude:
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - 'interactive_brokers_proxy/tmp/**/*'

Metrics/CyclomaticComplexity:
  Max: 10

Security/Eval:
  Exclude:
    - 'interactive_brokers_generator/spec/interactive_brokers_generator/class_source_generator_spec.rb'

Metrics/BlockLength:
  Exclude:
    - 'interactive_brokers_generator/spec/**/*'
    - 'interactive_brokers_proxy/spec/**/*'
    - 'interactive_brokers_common/spec/**/*'
    - '**/*.gemspec'

RSpec/NestedGroups:
  Exclude:
    - 'interactive_brokers_proxy/spec/interactive_brokers_proxy/java_method_dynamic_converter_spec.rb'
    - 'interactive_brokers_proxy/spec/interactive_brokers_proxy/registry_spec.rb'
    - 'interactive_brokers_common/spec/interactive_brokers_common/common/**/*'

RSpec/BeforeAfterAll:
  Exclude:
    - 'interactive_brokers_generator/spec/interactive_brokers_generator/class_source_generator_spec.rb'

RSpec/ExampleLength:
  Exclude:
    - 'interactive_brokers_generator/spec/interactive_brokers_generator/class_source_generator_spec.rb'
    - 'interactive_brokers_generator/spec/interactive_brokers_generator/class_source_generator_spec.rb'

RSpec/MultipleExpectations:
  Exclude:
   - 'interactive_brokers_generator/spec/interactive_brokers_generator/class_source_generator_spec.rb'

RSpec/EmptyExampleGroup:
  Exclude:
    - 'interactive_brokers_common/spec/interactive_brokers_common/common/**/*.rb'

RSpec/MultipleMemoizedHelpers:
  Exclude:
    - 'interactive_brokers_proxy/spec/interactive_brokers_proxy/java_method_dynamic_converter_spec.rb'

Style/GlobalVars:
  Exclude:
    - 'interactive_brokers_proxy/features/support/env.rb'

Naming/MethodName:
  Exclude:
    - 'interactive_brokers_proxy/lib/interactive_brokers_proxy/wrapper.rb'
