version: 2.1
defaults: &defaults
  working_directory: ~/interactive_brokers
  docker:
    - image: circleci/jruby:9.2.13.0-jdk11-node-browsers-legacy
      environment:
        BUNDLE_PATH: vendor/bundle
commands:
  prepare:
    description: "Common preparation steps"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install bundler
          command: |
            gem install bundler

      - run:
          name: install dependencies
          command: |
            bundle config set path 'vendor/bundle'
            bundle install --jobs=4 --retry=3
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

jobs:
  proxy_tests:
    <<: *defaults
    steps:
      - prepare
      - run:
          name: run tests
          command: |
            cd interactive_brokers_proxy
            mkdir /tmp/test-results

            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"

            bundle exec rspec --format progress \
                            --format RspecJunitFormatter \
                            --out /tmp/test-results/rspec.xml \
                            --tag ~type:performance \
                            $TEST_FILES

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
  generator_tests:
    <<: *defaults
    steps:
      - prepare
      - run:
          name: run tests
          command: |
            cd interactive_brokers_generator
            mkdir /tmp/test-results

            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"

            bundle exec rspec --format progress \
                            --format RspecJunitFormatter \
                            --out /tmp/test-results/rspec.xml \
                            --tag ~type:performance \
                            $TEST_FILES

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
  common_tests:
    <<: *defaults
    steps:
      - prepare
      - run:
          name: run tests
          command: |
            cd interactive_brokers_common
            mkdir /tmp/test-results

            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"

            bundle exec rspec --format progress \
                            --format RspecJunitFormatter \
                            --out /tmp/test-results/rspec.xml \
                            --tag ~type:performance \
                            $TEST_FILES

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
  rubocop:
    <<: *defaults
    steps:
      - prepare
      - run:
          name: Rubocop
          command: bundle exec rubocop
workflows:
  version: 2
  pipeline:
    jobs:
      - proxy_tests
      - generator_tests
      - common_tests
      - rubocop
